build:
	./gradlew build

test1:
	./build/install/app/bin/app src/test/resources/file1.json src/test/resources/file2.json

test2:
	./build/install/app/bin/app src/test/resources/file3.yaml src/test/resources/file4.yaml

help:
	./build/install/app/bin/app -h

jacoco:
	./gradlew jacocoTestReport

.PHONY: build



