name: build-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setyp Java
        uses: oracle-actions/setup-java@v1
        with:
          release: 20
      - name: Make Build
        run: |
          cd app
          make build

