name: build-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setyp Java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'oracle'
      - name: Make Build
        run: make -C app build
      - name: Codeclimate Coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make -C app jacoco
          coverageLocation: app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
